[package]
name = "tritium"
description = "The reference virtual machine implementing TRISC-27"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
trit-core.workspace = true

[lib]
name = "tritium"
path = "src/lib.rs"

[[bin]]
name = "tritium"
path = "src/main.rs"

[lints.rust]
missing_docs = "warn"
