//! Code generation: legalized TIR to TRISC-27 assembly.
//!
//! The output is assembly text rather than an image, so the assembler owns
//! label resolution, instruction encoding and layout — one implementation of
//! each, in `tritium`, shared with the disassembler. It also means the
//! backend's output is readable, which matters a great deal while it is new.
//!
//! # Where a value lives
//!
//! Every SSA value gets a stack slot, and that slot is the floor: an
//! instruction whose operands are not in registers loads them into scratch,
//! computes, and stores the result back. Above that floor sits `allocate`, a
//! linear scan over live intervals that decides once, for the whole function,
//! which values never touch memory at all.
//!
//! Two things follow. A **parameter** arrives in `a0`…`a7` and, in a function
//! that makes no call, has no reason to leave: nothing can clobber it there.
//! And a function whose values all fit in registers touches no frame, so it
//! opens none — which is why `function` needs the measuring pass to tell it
//! whether this one did.
//!
//! # Constants
//!
//! Every operation but `wrap` has an immediate form (TRISC-27 §4.1), so a
//! constant operand is folded into the encoding rather than materialized with
//! `li` into a scratch register — see `immediate` and `Gen::binary`. Measured
//! on `examples/trust/HPL.tr`, that fold alone was 10% of the instructions the
//! program executed.
//!
//! # Branches, and the two passes they need
//!
//! A `br3` displacement reaches ±1093 words (TRISC-27 §4.5), and a branch
//! that cannot reach is an assembly-time error rather than something the
//! assembler expands — expansion would make an instruction's size depend on
//! its operands. Code generation therefore has to know how far away a block
//! is before it can name it, which is why `function` runs `emit_function`
//! twice: the first pass sends every arm through an adjacent stub and records
//! where each block landed, and the second lets `br3` name the arms it can
//! reach. The second pass only removes instructions, so no distance it sees
//! is longer than the one the first measured.
//!
//! An arm still needs a stub when its target takes block arguments — the edge
//! has code, and it has to live somewhere — or when the target is genuinely
//! far. On `examples/trust/HPL.tr` that leaves 12% of the jumps that used to
//! be there.

use crate::tir::ir::*;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use trit_core::{FaultCode, Flavor};

/// Why a module could not be compiled.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct CodegenError {
    /// The function involved, if any.
    pub function: Option<String>,
    /// What could not be done.
    pub message: String,
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.function {
            Some(n) => write!(f, "@{n}: {}", self.message),
            None => write!(f, "{}", self.message),
        }
    }
}

impl std::error::Error for CodegenError {}

/// Trytes in a word.
const WORD: i128 = 3;

/// The reach of an I-format immediate: 14 trits, so (3¹⁴ − 1)/2 either way
/// (TRISC-27 §3.2).
const IMM_MAX: i128 = 2_391_484;

/// The immediate an operand carries, if it is a constant the I formats can
/// hold.
///
/// Every operation but `wrap` has both forms, spelled with an `i` suffix and
/// taking the immediate where the register form takes `rs2` (TRISC-27 §4.1).
/// Folding a constant into that field is worth doing everywhere it is legal:
/// the alternative is `li` into a scratch register, which is a whole
/// instruction spent on a number the encoding had room for.
fn immediate(o: &Operand) -> Option<i128> {
    match o {
        Operand::Const(_, v) => match v.to_i128() {
            Some(n) if n.abs() <= IMM_MAX => Some(n),
            _ => None,
        },
        _ => None,
    }
}

/// Round up to a whole number of words.
fn round_up(v: i128) -> i128 {
    (v + WORD - 1) / WORD * WORD
}

/// Compile a legalized module to TRISC-27 assembly.
///
/// `entry` names the function the generated start code calls; its result
/// becomes the machine's exit status.
pub fn compile(m: &Module, entry: &str) -> Result<String, Vec<CodegenError>> {
    let mut errs = Vec::new();
    let mut out = String::new();

    if m.function(entry).is_none() {
        errs.push(CodegenError {
            function: None,
            message: format!("`@{entry}` is not defined in this module"),
        });
    }

    // Only what the generated code actually uses: the device region is
    // unreachable from TIR (§5 has no integer-to-pointer cast), so the
    // character ports are the runtime's business, not this file's.
    let _ = writeln!(
        out,
        "; Generated by trustc from TIR. Target: TRISC-27.\n\
         \n\
         .equ MEM_SIZE, -6\n"
    );

    // Execution begins at address 0 (TRISC-27 §6.4), so the start code is
    // first: give the program a stack, call the entry function, and halt with
    // whatever it returned.
    let _ = writeln!(
        out,
        "_start:\n\
         \x20   ld.word sp, MEM_SIZE(zero)\n\
         \x20   call    f.{entry}\n\
         \x20   halt    a0\n"
    );

    for f in &m.funcs {
        match function(f) {
            Ok(text) => out.push_str(&text),
            Err(msgs) => errs.extend(msgs.into_iter().map(|message| CodegenError {
                function: Some(f.sig.name.clone()),
                message,
            })),
        }
    }

    for g in &m.globals {
        let _ = writeln!(out, "\n.align 3\ng.{}:", g.name);
        match &g.init {
            None => {
                let _ = writeln!(out, "    .zero {}", g.trytes);
            }
            Some(vals) => {
                // A relocation is emitted as a word holding the symbol's
                // address, which is where TIR §1.2's "the target decides the
                // number" is discharged.
                for item in vals {
                    match item {
                        InitItem::Tryte(v) => {
                            let _ = writeln!(out, "    .tryte {}", v.to_decimal());
                        }
                        InitItem::Addr(name) => {
                            let _ = writeln!(out, "    .word f.{name}");
                        }
                    }
                }
            }
        }
    }

    if errs.is_empty() { Ok(out) } else { Err(errs) }
}

/// Where a value lives: a displacement from `sp`.
struct Frame {
    /// Slot of each SSA value, in trytes from `sp`.
    slots: BTreeMap<String, i128>,
    /// Slots holding branch arguments in transit.
    transfer: Vec<i128>,
    /// Total frame size in trytes.
    size: i128,
}

/// Lay out the frame: one word per SSA value, plus `slot` storage, plus a
/// transfer area wide enough for the widest block parameter list.
///
/// The transfer area is what makes a jump with block arguments safe when an
/// argument reads a slot another argument is about to write — the loop back
/// edge that swaps two values is the case that matters. Arguments go to the
/// transfer slots first, and only then to the parameters.
fn layout(f: &Function, saved: &[&'static str]) -> Frame {
    let mut slots = BTreeMap::new();
    let mut cursor = WORD; // word 0 holds the saved return address

    // Then one word per callee-saved register the allocator used.
    for r in saved {
        slots.insert(format!("\u{1}saved.{r}"), cursor);
        cursor += WORD;
    }

    let mut give = |name: &str, cursor: &mut i128| {
        slots.entry(name.to_string()).or_insert_with(|| {
            let at = *cursor;
            *cursor += WORD;
            at
        });
    };

    for (n, _) in &f.sig.params {
        give(n, &mut cursor);
    }
    for b in &f.blocks {
        for (n, _) in &b.params {
            give(n, &mut cursor);
        }
        for i in &b.insts {
            for r in &i.results {
                give(r, &mut cursor);
            }
        }
    }

    // `slot` allocations are storage, not values: the value is the address.
    for b in &f.blocks {
        for i in &b.insts {
            if let InstKind::Slot { trytes } = &i.kind {
                let aligned = round_up(cursor);
                cursor = aligned + round_up(*trytes as i128);
                if let Some(name) = i.results.first() {
                    slots.insert(format!("\u{1}storage.{name}"), aligned);
                }
            }
        }
    }

    let widest = f.blocks.iter().map(|b| b.params.len()).max().unwrap_or(0);
    let transfer: Vec<i128> = (0..widest)
        .map(|_| {
            let at = cursor;
            cursor += WORD;
            at
        })
        .collect();

    Frame {
        slots,
        transfer,
        size: round_up(cursor),
    }
}

/// An address a load or store can carry in its own displacement field.
#[derive(Clone)]
struct Folded {
    /// What the displacement is measured from.
    base: Base,
    /// Trytes from that base.
    disp: i128,
}

#[derive(Clone)]
enum Base {
    /// The frame, at the storage a `slot` instruction reserved — so the base
    /// register is `sp`, which is always available and never allocated.
    Slot(String),
    /// Another value, which has to be in a register at the access.
    Value(Operand),
}

/// The addresses this block computes that its loads and stores can carry
/// themselves.
///
/// `ld` and `st` take a fourteen-trit displacement (TRISC-27 §3.2) and code
/// generation was leaving it at zero, emitting an `add` for every address it
/// had already been given a field for. Two shapes produce a foldable address:
/// `%p = offset %b, const k`, and `%p = slot n`, whose value is a fixed
/// displacement from `sp`.
///
/// Folding drops the address computation entirely, so it is sound only when
/// **every** use of the value is a pointer operand of an access, and every
/// one of those is in this block — otherwise something else still needs the
/// address in a register. There is nothing to preserve about the arithmetic
/// itself: `offset` performs no bounds reasoning, and leaving an allocation's
/// provenance is already UB (TIR §§3.4, 4).
fn block_folds(f: &Function, block: &Block) -> BTreeMap<String, Folded> {
    // Candidates, before asking how they are used.
    let mut candidates: BTreeMap<String, Folded> = BTreeMap::new();
    for inst in &block.insts {
        let Some(r) = inst.results.first() else {
            continue;
        };
        let found = match &inst.kind {
            InstKind::Slot { .. } => Some(Folded {
                base: Base::Slot(r.clone()),
                disp: 0,
            }),
            InstKind::Offset { p, d } => immediate(d).map(|k| Folded {
                base: Base::Value(p.clone()),
                disp: k,
            }),
            _ => None,
        };
        if let Some(fold) = found {
            candidates.insert(r.clone(), fold);
        }
    }
    if candidates.is_empty() {
        return candidates;
    }

    // Every use, counted twice: once for all of them, once for the ones an
    // access could carry. A candidate survives iff the two agree.
    let mut all: BTreeMap<String, usize> = BTreeMap::new();
    let mut foldable: BTreeMap<String, usize> = BTreeMap::new();
    for b in &f.blocks {
        let here = b.label == block.label;
        for inst in &b.insts {
            if let InstKind::Load { p, .. } | InstKind::Store { p, .. } = &inst.kind
                && let Operand::Value(n) = p
                && here
            {
                *foldable.entry(n.clone()).or_default() += 1;
            }
            operands_of(&inst.kind, &mut |o| {
                if let Operand::Value(n) = o {
                    *all.entry(n.clone()).or_default() += 1;
                }
            });
        }
        terminator_operands(&b.term, &mut |o| {
            if let Operand::Value(n) = o {
                *all.entry(n.clone()).or_default() += 1;
            }
        });
    }

    candidates.retain(|name, _| {
        let n = foldable.get(name).copied().unwrap_or(0);
        n > 0 && n == all.get(name).copied().unwrap_or(0)
    });
    candidates
}

/// Visit every operand an instruction reads, as the emitter will actually
/// read it: an access whose address was folded reads the base instead of the
/// address, and the folded-away computation reads nothing at all.
fn effective_operands(
    k: &InstKind,
    folds: &BTreeMap<String, Folded>,
    f: &mut impl FnMut(&Operand),
) {
    let folded = |p: &Operand| match p {
        Operand::Value(n) => folds.get(n),
        _ => None,
    };
    match k {
        InstKind::Load { p, .. } => match folded(p) {
            Some(Folded {
                base: Base::Value(b),
                ..
            }) => f(b),
            Some(_) => {}
            None => f(p),
        },
        InstKind::Store { v, p, .. } => {
            f(v);
            match folded(p) {
                Some(Folded {
                    base: Base::Value(b),
                    ..
                }) => f(b),
                Some(_) => {}
                None => f(p),
            }
        }
        _ => operands_of(k, f),
    }
}

/// Visit every operand an instruction reads.
fn operands_of(k: &InstKind, f: &mut impl FnMut(&Operand)) {
    match k {
        InstKind::Flavored { a, b, .. } | InstKind::Plain { a, b, .. } => {
            f(a);
            f(b);
        }
        InstKind::Cmp { a, b, .. } => {
            f(a);
            f(b);
        }
        InstKind::Neg { a, .. } | InstKind::Widen { a, .. } | InstKind::Trunc { a, .. } => f(a),
        InstKind::Select3 {
            t, neg, zero, pos, ..
        } => {
            f(t);
            f(neg);
            f(zero);
            f(pos);
        }
        InstKind::Slot { .. } => {}
        InstKind::Load { p, .. } => f(p),
        InstKind::Store { v, p, .. } => {
            f(v);
            f(p);
        }
        InstKind::Offset { p, d } => {
            f(p);
            f(d);
        }
        InstKind::Call { callee, args, .. } => {
            if let Callee::Indirect(p) = callee {
                f(p);
            }
            args.iter().for_each(f);
        }
    }
}

/// Visit every operand a terminator reads, block arguments included.
fn terminator_operands(t: &Terminator, f: &mut impl FnMut(&Operand)) {
    match t {
        Terminator::Br3 { t, neg, zero, pos } => {
            f(t);
            for d in [neg, zero, pos] {
                d.args.iter().for_each(&mut *f);
            }
        }
        Terminator::Br(d) => d.args.iter().for_each(f),
        Terminator::Ret(Some(v)) => f(v),
        Terminator::Ret(None) | Terminator::Trap(_) | Terminator::Unreachable => {}
    }
}

/// Registers a block-local value may be kept in.
///
/// `t0`…`t3` are the scratch every emitter uses and are never allocated.
/// `t4`…`t7` are always available. `a0`…`a7` are too, but only in a block
/// that makes no call: they are the argument registers, so a call both
/// clobbers them and overwrites them while its arguments are set up.
const POOL_ALWAYS: &[&str] = &["t4", "t5", "t6", "t7"];
const POOL_CALL_FREE: &[&str] = &["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7"];
/// Callee-saved (TRISC-27 §6.1), so a value in one survives a call. Using one
/// costs a save in the prologue and a restore in the epilogue, so they are
/// handed out only to a range that actually crosses a call — the range no
/// caller-saved register can hold.
const POOL_SAVED: &[&str] = &["s0", "s1", "s2", "s3", "s4", "s5", "s6"];

/// How far a `br3` displacement reaches: seven trits of words, so ±1093
/// (TRISC-27 §3.2). A margin is left because the estimate below has to agree
/// with the assembler's own sizing, and being wrong here is an assembly-time
/// error rather than a slower program.
const BR3_REACH: i128 = 1000;

/// How many words a line of generated assembly assembles to.
///
/// Every instruction is one word. The two pseudo-instructions that are not
/// are `li`, which is one word when the value fits the fourteen-trit
/// immediate and two otherwise, and `la`, which is always two (`vm/src/asm.rs`
/// — a forward reference must not change a statement's size).
fn words_of(line: &str) -> i128 {
    let t = line.trim_start();
    if let Some(rest) = t.strip_prefix("li ") {
        let v: Option<i128> = rest.rsplit(',').next().and_then(|n| n.trim().parse().ok());
        return match v {
            Some(n) if n.abs() <= IMM_MAX => 1,
            _ => 2,
        };
    }
    if t.starts_with("la ") { 2 } else { 1 }
}

struct Gen<'a> {
    func: &'a Function,
    frame: Frame,
    out: String,
    errs: Vec<String>,
    counter: u32,
    /// Words emitted so far, counted the way the assembler counts them.
    here: i128,
    /// Word offset of each block, from the measuring pass. Empty during that
    /// pass, when every branch takes the long way.
    offsets: BTreeMap<String, i128>,
    /// The block emitted after the one being emitted, if any: a branch to it
    /// needs no jump at all.
    next_block: Option<String>,
    /// Addresses the block's accesses carry in their own displacement, whose
    /// computations are therefore not emitted at all.
    folds: BTreeMap<String, Folded>,
    /// Whether anything in the body actually touched the frame. A function
    /// that never did needs no frame, and therefore neither of the two
    /// instructions that open and close one. The measuring pass observes it;
    /// the final pass is told the answer, because the epilogue is emitted at
    /// every `ret` and one of them may precede the first frame access.
    frame_used: bool,
    /// What the measuring pass concluded.
    frame_needed: bool,
    /// Where every value lives, for the whole function. A value not here
    /// lives in its frame slot, as every value did before there was an
    /// allocator.
    regs: BTreeMap<String, &'static str>,
}

/// Where every value lives, decided once for the whole function.
///
/// This is a linear scan over live intervals — the classical shape, with the
/// parts this machine and this frontend make simpler or harder called out
/// below. It replaced a block-local allocator that could keep a value in a
/// register only when one block both defined and used it; everything crossing
/// an edge went to memory, and on `examples/trust/HPL.tr` that traffic was
/// 44% of every instruction executed, against 15% for the program's own data.
///
/// **Liveness.** The interval of a value is the hull of every point it is
/// live at: its definition, its uses, and the start of every block it is
/// live into and the end of every block it is live out of (`liveness`). The
/// hull matters for loops — a value defined inside one and read at the top of
/// the next iteration is live at a point *earlier* in the linear order than
/// its definition, and an interval that did not reach back would let another
/// value take the register there.
///
/// **Block parameters are left in memory.** A parameter has a different
/// definition on each incoming edge, so agreeing on a register for it is the
/// parallel-copy problem, and `move_args` already solves it with a transfer
/// area in the frame. The frontend emits no block parameters at all
/// (`lang/lower.rs`: every local is a slot, so nothing crosses an edge in a
/// register), so this costs real programs nothing; hand-written TIR uses
/// them, and keeps working.
///
/// **Which registers.** `t0`…`t3` are the scratch the emitters use and are
/// never allocated. `t4`…`t7` are caller-saved and free to take. `a0`…`a7`
/// are caller-saved too, but a call writes them while setting up its own
/// arguments, so they are allocated only in a function that makes no call —
/// where that cannot happen, and where a parameter can simply stay in the
/// register it arrived in. `s0`…`s6` survive a call (TRISC-27 §6.1) at the
/// cost of a save and a restore.
///
/// **What a callee-saved register is worth.** It is paid once per
/// *invocation*; a spill is paid once per *use*. So an interval that crosses
/// a call takes one only when the value is used more than once — measured,
/// not assumed: handing one to every call-crossing value made a recursive
/// benchmark 6% slower (G8.3).
fn allocate(f: &Function, folds: &[BTreeMap<String, Folded>]) -> BTreeMap<String, &'static str> {
    let pos = positions(f);
    let (live_in, live_out) = liveness(f, folds);

    // A block parameter is defined by its predecessors, not here.
    let mut excluded: BTreeSet<String> = BTreeSet::new();
    for b in &f.blocks {
        for (n, _) in &b.params {
            excluded.insert(n.clone());
        }
    }

    // Every point each value is live at, collapsed to a first and a last.
    let mut span: BTreeMap<String, (usize, usize)> = BTreeMap::new();
    let mut uses: BTreeMap<String, usize> = BTreeMap::new();
    let mark = |span: &mut BTreeMap<String, (usize, usize)>, v: &str, at: usize| {
        span.entry(v.to_string())
            .and_modify(|(lo, hi)| {
                *lo = (*lo).min(at);
                *hi = (*hi).max(at);
            })
            .or_insert((at, at));
    };

    // A parameter is live from the entry block's entry, which is before its
    // first instruction — a call there is one the parameter is live across.
    for (n, _) in &f.sig.params {
        mark(&mut span, n, 0);
    }
    for (bi, b) in f.blocks.iter().enumerate() {
        for n in &live_in[bi] {
            mark(&mut span, n, pos.block_start[bi]);
        }
        for n in &live_out[bi] {
            mark(&mut span, n, pos.block_term[bi]);
        }
        let mut at = pos.block_start[bi] + 1;
        for inst in &b.insts {
            if !inst.results.iter().any(|r| folds[bi].contains_key(r)) {
                effective_operands(&inst.kind, &folds[bi], &mut |o| {
                    if let Operand::Value(v) = o {
                        mark(&mut span, v, at);
                        *uses.entry(v.clone()).or_default() += 1;
                    }
                });
            }
            for r in &inst.results {
                mark(&mut span, r, at);
            }
            at += 1;
        }
        terminator_operands(&b.term, &mut |o| {
            if let Operand::Value(v) = o {
                mark(&mut span, v, at);
                *uses.entry(v.clone()).or_default() += 1;
            }
        });
    }

    // A value the accesses absorbed, or one nothing ever reads, needs
    // nowhere to be.
    span.retain(|n, _| {
        !excluded.contains(n) && !folds.iter().any(|m| m.contains_key(n)) && uses.contains_key(n)
    });

    let calls = &pos.calls;
    // A call is crossed only by a value that is still live after it
    // returns. A value whose last use is an *argument* to the call is read
    // while the arguments are set up, before the call executes, so a
    // caller-saved register holds it perfectly well; so does the call's own
    // result, which arrives after everything is clobbered.
    let crosses_call = |lo: usize, hi: usize| calls.iter().any(|c| lo < *c && *c < hi);
    let function_calls = !calls.is_empty();

    let mut fast: Vec<&'static str> = POOL_ALWAYS.to_vec();
    if !function_calls {
        fast.extend_from_slice(POOL_CALL_FREE);
    }
    let mut saved: Vec<&'static str> = POOL_SAVED.to_vec();
    let mut regs: BTreeMap<String, &'static str> = BTreeMap::new();
    // Registers in use, with the point their value dies.
    let mut active: Vec<(usize, &'static str, bool)> = Vec::new();

    // A parameter arrives in `a0`…`a7`, and in a function that makes no call
    // nothing can take it from there. Claiming its own register first is what
    // makes the prologue emit nothing at all for it.
    if !function_calls {
        for (i, (pname, _)) in f.sig.params.iter().enumerate().take(POOL_CALL_FREE.len()) {
            let Some((_, hi)) = span.get(pname).copied() else {
                continue;
            };
            let r = POOL_CALL_FREE[i];
            if !fast.contains(&r) {
                continue;
            }
            fast.retain(|x| *x != r);
            regs.insert(pname.clone(), r);
            active.push((hi, r, false));
        }
    }

    // Linear scan: intervals in order of where they begin.
    let mut order: Vec<(usize, usize, String)> = span
        .iter()
        .filter(|(n, _)| !regs.contains_key(*n))
        .map(|(n, (lo, hi))| (*lo, *hi, n.clone()))
        .collect();
    order.sort();

    for (lo, hi, name) in order {
        active.retain(|(end, r, is_saved)| {
            if *end < lo {
                if *is_saved {
                    saved.push(r)
                } else {
                    fast.push(r)
                }
                false
            } else {
                true
            }
        });
        let needs_saved = crosses_call(lo, hi);
        if needs_saved && uses.get(&name).copied().unwrap_or(0) < 2 {
            continue;
        }
        let picked = if needs_saved {
            saved.pop().map(|r| (r, true))
        } else {
            fast.pop()
                .map(|r| (r, false))
                .or_else(|| saved.pop().map(|r| (r, true)))
        };
        if let Some((r, is_saved)) = picked {
            regs.insert(name, r);
            active.push((hi, r, is_saved));
            continue;
        }

        // Nothing free. Spilling *this* interval is the easy answer and the
        // wrong one: an interval that ends further away occupies its register
        // for longer and is therefore worth less per instruction it saves. So
        // take the register from whichever active interval runs longest, if
        // that one runs longer than this.
        let candidate = active
            .iter()
            .enumerate()
            .filter(|(_, (_, r, is_saved))| {
                // A value living across a call cannot be moved into a
                // caller-saved register, so only like may replace like.
                *is_saved
                    || !needs_saved && POOL_ALWAYS.contains(r)
                    || !needs_saved && POOL_CALL_FREE.contains(r)
            })
            .max_by_key(|(_, (end, _, _))| *end);
        let Some((i, (end, r, is_saved))) = candidate.map(|(i, e)| (i, *e)) else {
            continue;
        };
        if end <= hi {
            continue;
        }
        // The evicted value goes back to its frame slot, which is where every
        // value lives by default.
        regs.retain(|_, held| *held != r);
        active.swap_remove(i);
        regs.insert(name, r);
        active.push((hi, r, is_saved));
    }
    regs
}

/// Where each block begins and ends in one linear numbering of the function,
/// and where the calls are.
///
/// A block's *entry* gets a position of its own, strictly before its first
/// instruction, and so does its terminator. Both matter. A value live into a
/// block whose first instruction is a call is live across that call, and an
/// interval that began *at* the call would not say so — which is exactly how
/// a function parameter read after the first call came to be given a
/// caller-saved register.
struct Positions {
    /// A point before the block's first instruction, where its parameters
    /// are bound and where anything live into it is already live.
    block_start: Vec<usize>,
    /// The index of a block's terminator, which runs after its instructions.
    block_term: Vec<usize>,
    calls: Vec<usize>,
}

fn positions(f: &Function) -> Positions {
    let mut p = Positions {
        block_start: Vec::with_capacity(f.blocks.len()),
        block_term: Vec::with_capacity(f.blocks.len()),
        calls: Vec::new(),
    };
    let mut at = 0usize;
    for b in &f.blocks {
        p.block_start.push(at);
        at += 1;
        for inst in &b.insts {
            if matches!(inst.kind, InstKind::Call { .. }) {
                p.calls.push(at);
            }
            at += 1;
        }
        p.block_term.push(at);
        at += 1;
    }
    p
}

/// Live-in and live-out sets, by the usual backward fixpoint.
///
/// `use[b]` is what the block reads before defining, `def[b]` what it
/// defines — its parameters included, since they are bound on entry.
fn liveness(
    f: &Function,
    folds: &[BTreeMap<String, Folded>],
) -> (Vec<BTreeSet<String>>, Vec<BTreeSet<String>>) {
    let n = f.blocks.len();
    let mut used: Vec<BTreeSet<String>> = vec![BTreeSet::new(); n];
    let mut defined: Vec<BTreeSet<String>> = vec![BTreeSet::new(); n];
    let mut succ: Vec<Vec<usize>> = vec![Vec::new(); n];
    let index: BTreeMap<&str, usize> = f
        .blocks
        .iter()
        .enumerate()
        .map(|(i, b)| (b.label.as_str(), i))
        .collect();

    for (bi, b) in f.blocks.iter().enumerate() {
        for (p, _) in &b.params {
            defined[bi].insert(p.clone());
        }
        for inst in &b.insts {
            if !inst.results.iter().any(|r| folds[bi].contains_key(r)) {
                effective_operands(&inst.kind, &folds[bi], &mut |o| {
                    if let Operand::Value(v) = o
                        && !defined[bi].contains(v)
                    {
                        used[bi].insert(v.clone());
                    }
                });
            }
            for r in &inst.results {
                defined[bi].insert(r.clone());
            }
        }
        let mut reads = BTreeSet::new();
        terminator_operands(&b.term, &mut |o| {
            if let Operand::Value(v) = o {
                reads.insert(v.clone());
            }
        });
        for v in reads {
            if !defined[bi].contains(&v) {
                used[bi].insert(v);
            }
        }
        for label in successors(&b.term) {
            if let Some(j) = index.get(label.as_str()) {
                succ[bi].push(*j);
            }
        }
    }

    let mut live_in: Vec<BTreeSet<String>> = vec![BTreeSet::new(); n];
    let mut live_out: Vec<BTreeSet<String>> = vec![BTreeSet::new(); n];
    let mut changed = true;
    while changed {
        changed = false;
        for bi in (0..n).rev() {
            let mut out = BTreeSet::new();
            for &j in &succ[bi] {
                out.extend(live_in[j].iter().cloned());
            }
            let mut into = used[bi].clone();
            into.extend(out.iter().filter(|v| !defined[bi].contains(*v)).cloned());
            if out != live_out[bi] || into != live_in[bi] {
                live_out[bi] = out;
                live_in[bi] = into;
                changed = true;
            }
        }
    }
    (live_in, live_out)
}

/// The blocks a terminator may transfer to.
fn successors(t: &Terminator) -> Vec<String> {
    match t {
        Terminator::Br3 { neg, zero, pos, .. } => {
            vec![neg.label.clone(), zero.label.clone(), pos.label.clone()]
        }
        Terminator::Br(d) => vec![d.label.clone()],
        Terminator::Ret(_) | Terminator::Trap(_) | Terminator::Unreachable => Vec::new(),
    }
}

/// The callee-saved registers a function's allocation uses, in order — what
/// the prologue must save and the epilogue restore.
fn saved_registers(regs: &BTreeMap<String, &'static str>) -> Vec<&'static str> {
    let mut used: BTreeSet<&'static str> = BTreeSet::new();
    for r in regs.values() {
        if POOL_SAVED.contains(r) {
            used.insert(r);
        }
    }
    used.into_iter().collect()
}

impl Gen<'_> {
    fn line(&mut self, text: impl AsRef<str>) {
        let text = text.as_ref();
        self.here += words_of(text);
        // Any mention of `sp` but the frame adjust itself: an access
        // through it, or an address taken from it.
        self.frame_used |= text.contains("sp") && !text.starts_with("addi.trap sp, sp,");
        let _ = writeln!(self.out, "    {text}");
    }

    fn label(&mut self, text: impl AsRef<str>) {
        let _ = writeln!(self.out, "{}:", text.as_ref());
    }

    /// Whether a `br3` here can name this target itself, rather than a jump
    /// standing in for it.
    ///
    /// Two things stop it. A target with block arguments needs code on the
    /// edge to bind them, and the only place to put that code is a stub. And
    /// a target out of the displacement's reach needs a jump, whose range is
    /// the whole address space.
    ///
    /// The reach is judged by the measuring pass's layout, which is sound
    /// because this pass only *removes* instructions: no distance it computes
    /// is longer than the one measured.
    fn reaches(&self, target: &Target) -> bool {
        if !target.args.is_empty() {
            return false;
        }
        match self.offsets.get(&target.label) {
            Some(at) => (at - self.here).abs() <= BR3_REACH,
            None => false,
        }
    }

    fn fresh(&mut self, what: &str) -> String {
        self.counter += 1;
        // The function's name is part of it: a local label is file-scoped,
        // and the counter restarts with every function.
        format!(".L{}.{what}{}", self.func.sig.name, self.counter)
    }

    fn slot(&mut self, name: &str) -> i128 {
        match self.frame.slots.get(name) {
            Some(s) => *s,
            None => {
                self.errs.push(format!("`%{name}` has no slot"));
                0
            }
        }
    }

    /// Load an operand into a register.
    /// The register an operand's value is in, materializing it into
    /// `scratch` when it is not already somewhere.
    ///
    /// A value the allocator kept in a register costs **no instruction at
    /// all** here, which is the whole point: the frame-slot scheme spent a
    /// load on every operand of every instruction.
    fn read(&mut self, o: &Operand, scratch: &str) -> String {
        match o {
            Operand::Value(name) => {
                if let Some(r) = self.regs.get(name) {
                    return (*r).to_string();
                }
                let at = self.slot(name);
                self.line(format!("ld.word {scratch}, {at}(sp)"));
            }
            Operand::Const(_, v) => {
                self.line(format!("li      {scratch}, {}", v.to_decimal()));
            }
            Operand::Global(g) => {
                self.line(format!("la      {scratch}, g.{g}"));
            }
        }
        scratch.to_string()
    }

    /// Where to compute a result: its own register if it has one, otherwise
    /// the scratch it will be stored from.
    fn dest(&mut self, name: Option<&String>, scratch: &str) -> String {
        match name.and_then(|n| self.regs.get(n)) {
            Some(r) => (*r).to_string(),
            None => scratch.to_string(),
        }
    }

    /// Emit a binary operation, taking the immediate form when an operand is
    /// a constant the field can hold.
    ///
    /// `commutative` says whether the operands may be exchanged, which is
    /// what lets `3 * x` reach the immediate form as readily as `x * 3`. The
    /// operations where it is false are the ones an exchange would change:
    /// `sub`, the shifts, `div`, `rem`, and `cmp`, whose result an exchange
    /// negates.
    fn binary(
        &mut self,
        stem: &str,
        suffix: &str,
        commutative: bool,
        a: &Operand,
        b: &Operand,
        result: Option<&String>,
    ) {
        let folded = match (immediate(b), immediate(a)) {
            (Some(n), _) => Some((a, n)),
            (None, Some(n)) if commutative => Some((b, n)),
            _ => None,
        };
        let (rd, text) = match folded {
            Some((other, n)) => {
                let ro = self.read(other, "t0");
                let rd = self.dest(result, "t2");
                let m = format!("{stem}i{suffix}");
                (rd.clone(), format!("{m:<7} {rd}, {ro}, {n}"))
            }
            None => {
                let ra = self.read(a, "t0");
                let rb = self.read(b, "t1");
                let rd = self.dest(result, "t2");
                let m = format!("{stem}{suffix}");
                (rd.clone(), format!("{m:<7} {rd}, {ra}, {rb}"))
            }
        };
        self.line(text);
        if let Some(r) = result {
            self.write(r, &rd);
        }
    }

    /// The base register and displacement an access should use.
    ///
    /// When the address was folded (`block_folds`), the computation that
    /// would have produced it was never emitted, and the access carries the
    /// displacement itself.
    fn address(&mut self, p: &Operand, scratch: &str) -> (String, i128) {
        let fold = match p {
            Operand::Value(n) => self.folds.get(n).cloned(),
            _ => None,
        };
        match fold {
            None => (self.read(p, scratch), 0),
            Some(Folded {
                base: Base::Slot(name),
                disp,
            }) => {
                let at = self.slot(&format!("\u{1}storage.{name}"));
                ("sp".to_string(), at + disp)
            }
            Some(Folded {
                base: Base::Value(b),
                disp,
            }) => (self.read(&b, scratch), disp),
        }
    }

    /// Store a result to its slot, unless it lives in a register.
    fn write(&mut self, name: &str, reg: &str) {
        if self.regs.contains_key(name) {
            return;
        }
        let at = self.slot(name);
        self.line(format!("st.word {reg}, {at}(sp)"));
    }

    fn block_label(&self, block: &str) -> String {
        format!("f.{}.{}", self.func.sig.name, block)
    }
}

/// Generate a function, twice.
///
/// The first pass measures: it emits every branch the long way and records
/// where each block landed. The second uses those offsets to let a `br3`
/// name its targets directly wherever they are in reach — which is the common
/// case, and saves the jump that used to stand in for every one of them.
///
/// Two passes are needed and two suffice. The second only removes
/// instructions, so no distance it sees is longer than the one the first
/// measured, and a branch judged to reach still reaches.
fn function(f: &Function) -> Result<String, Vec<String>> {
    // Everything the two emission passes need to agree on is decided once,
    // here: which addresses the accesses absorb, where every value lives, and
    // therefore what the prologue has to save.
    let folds: Vec<BTreeMap<String, Folded>> = f.blocks.iter().map(|b| block_folds(f, b)).collect();
    let regs = allocate(f, &folds);
    let saved = saved_registers(&regs);
    let measured = emit_function(f, &saved, &folds, &regs, &BTreeMap::new(), true);
    let final_pass = emit_function(
        f,
        &saved,
        &folds,
        &regs,
        &measured.offsets,
        measured.frame_used,
    );
    if final_pass.errs.is_empty() {
        Ok(final_pass.out)
    } else {
        Err(final_pass.errs)
    }
}

fn emit_function<'a>(
    f: &'a Function,
    saved: &[&'static str],
    folds: &[BTreeMap<String, Folded>],
    regs: &BTreeMap<String, &'static str>,
    offsets: &BTreeMap<String, i128>,
    needs_frame: bool,
) -> Gen<'a> {
    // The frame has to hold whatever the allocator decided to save, so the
    // allocation is settled before the layout that depends on it.
    let frame = layout(f, saved);
    let calls = f.blocks.iter().any(|b| {
        b.insts
            .iter()
            .any(|i| matches!(i.kind, InstKind::Call { .. }))
    });

    let mut g = Gen {
        regs: regs.clone(),
        func: f,
        frame,
        out: String::new(),
        errs: Vec::new(),
        counter: 0,
        here: 0,
        offsets: offsets.clone(),
        next_block: None,
        folds: BTreeMap::new(),
        frame_used: false,
        frame_needed: needs_frame,
    };

    let name = f.sig.name.clone();
    let _ = writeln!(g.out, "\n; {} — frame {} trytes", name, g.frame.size);
    // Instructions are word-aligned (TRISC-27 §3.1), and data of a length
    // that is not a multiple of three may precede this.
    let _ = writeln!(g.out, ".align 3");
    g.label(format!("f.{name}"));

    // Prologue. `sp` grows downward and stays word-aligned (§6.2). A
    // function whose values all fit in registers touches no frame and opens
    // none: the measuring pass says whether this one does.
    let size = g.frame.size;
    if needs_frame {
        g.line(format!("addi.trap sp, sp, -{size}"));
    }
    if calls {
        g.line("st.word ra, 0(sp)");
    }
    // A callee-saved register belongs to whoever called us (TRISC-27 §6.1).
    for r in saved {
        let at = g.slot(&format!("\u{1}saved.{r}"));
        g.line(format!("st.word {r}, {at}(sp)"));
    }

    // Arguments arrive in a0…a7. One the allocator left where it arrived
    // needs nothing; one it put elsewhere is moved there once; the rest are
    // spilled to their slots.
    for (i, (pname, _)) in f.sig.params.iter().enumerate() {
        if i >= 8 {
            g.errs
                .push("more than eight arguments is not implemented".into());
            break;
        }
        match regs.get(pname) {
            Some(r) if *r == POOL_CALL_FREE[i] => {}
            Some(r) => g.line(format!("add.wrap {r}, a{i}, zero")),
            None => {
                let at = g.slot(pname);
                g.line(format!("st.word a{i}, {at}(sp)"));
            }
        }
    }
    // The entry block is emitted next, so the prologue falls into it.

    for (i, b) in f.blocks.iter().enumerate() {
        g.folds = folds[i].clone();
        let label = g.block_label(&b.label);
        g.offsets.insert(b.label.clone(), g.here);
        g.label(label);
        g.next_block = f.blocks.get(i + 1).map(|n| n.label.clone());
        for inst in &b.insts {
            emit_inst(&mut g, inst, calls);
        }
        emit_term(&mut g, &b.term, calls);
    }

    g
}

/// The epilogue, emitted at every `ret`.
fn epilogue(g: &mut Gen, calls: bool) {
    if calls {
        g.line("ld.word ra, 0(sp)");
    }
    let saved: Vec<String> = g
        .frame
        .slots
        .keys()
        .filter(|k| k.starts_with('\u{1}'))
        .filter_map(|k| k.strip_prefix("\u{1}saved.").map(str::to_string))
        .collect();
    for r in saved {
        let at = g.slot(&format!("\u{1}saved.{r}"));
        g.line(format!("ld.word {r}, {at}(sp)"));
    }
    let size = g.frame.size;
    if g.frame_needed {
        g.line(format!("addi.trap sp, sp, {size}"));
    }
    g.line("ret");
}

fn emit_inst(g: &mut Gen, inst: &Inst, _calls: bool) {
    // An address the accesses that use it absorbed needs no instruction.
    if inst
        .results
        .first()
        .is_some_and(|r| g.folds.contains_key(r))
    {
        return;
    }
    match &inst.kind {
        InstKind::Flavored {
            op,
            flavor,
            a,
            b,
            ty,
        } => {
            check_width(g, *ty);
            let mnemonic = match op {
                FlavoredOp::Add => "add",
                FlavoredOp::Sub => "sub",
                FlavoredOp::Mul => "mul",
                FlavoredOp::Shl => "shl",
            };
            let suffix = flavor.suffix();
            // The flag flavor names a second destination, and `alui` has no
            // field for it (TRISC-27 §4.1), so it keeps the register form.
            if *flavor == Flavor::Flag {
                let ra = g.read(a, "t0");
                let rb = g.read(b, "t1");
                let rd = g.dest(inst.results.first(), "t2");
                let rf = g.dest(inst.results.get(1), "t3");
                g.line(format!("{mnemonic}{suffix} {rd}, {ra}, {rb}, {rf}"));
                if let Some(r) = inst.results.first() {
                    g.write(r, &rd);
                }
                if let Some(r) = inst.results.get(1) {
                    g.write(r, &rf);
                }
            } else {
                let commutative = matches!(op, FlavoredOp::Add | FlavoredOp::Mul);
                g.binary(mnemonic, suffix, commutative, a, b, inst.results.first());
            }
        }

        InstKind::Plain { op, a, b, ty } => {
            check_width(g, *ty);
            let mnemonic = match op {
                PlainOp::MulH => "mulh",
                PlainOp::Div => "div",
                PlainOp::Rem => "rem",
                PlainOp::Shr => "shr",
                PlainOp::TMin => "tmin",
                PlainOp::TMax => "tmax",
                PlainOp::TMul => "tmul",
            };
            let commutative = matches!(
                op,
                PlainOp::MulH | PlainOp::TMin | PlainOp::TMax | PlainOp::TMul
            );
            g.binary(mnemonic, "", commutative, a, b, inst.results.first());
        }

        // Negation is `0 − x`; the machine needs no separate instruction
        // because `r0` is a register like any other (TRISC-27 §4.1).
        InstKind::Neg { a, ty } => {
            check_width(g, *ty);
            let ra = g.read(a, "t0");
            let rd = g.dest(inst.results.first(), "t2");
            g.line(format!("neg     {rd}, {ra}"));
            if let Some(r) = inst.results.first() {
                g.write(r, &rd);
            }
        }

        InstKind::Cmp { a, b, ty } => {
            check_width(g, *ty);
            g.binary("cmp", "", false, a, b, inst.results.first());
        }

        // One instruction, three arms, no branch.
        InstKind::Select3 {
            t,
            neg,
            zero,
            pos,
            ty,
        } => {
            check_width(g, *ty);
            let rt = g.read(t, "t0");
            let rn = g.read(neg, "t1");
            let rz = g.read(zero, "t2");
            let rp = g.read(pos, "t3");
            // The destination may alias a source: `sel3` reads its selector
            // and the chosen arm before it writes (TRISC-27 §4.2), which is
            // what lets the result go straight into its own register.
            let rd = g.dest(inst.results.first(), "t2");
            g.line(format!("sel3    {rd}, {rt}, {rn}, {rz}, {rp}"));
            if let Some(r) = inst.results.first() {
                g.write(r, &rd);
            }
        }

        // The value of a `slot` is the address of its storage in the frame.
        InstKind::Slot { .. } => {
            if let Some(r) = inst.results.first() {
                let at = g.slot(&format!("\u{1}storage.{r}"));
                let rd = g.dest(Some(r), "t0");
                g.line(format!("addi.trap {rd}, sp, {at}"));
                g.write(r, &rd);
            }
        }

        InstKind::Load { ty, p } => {
            let (rp, disp) = g.address(p, "t0");
            let width = access_width(g, *ty);
            let rd = g.dest(inst.results.first(), "t2");
            g.line(format!("ld.{width} {rd}, {disp}({rp})"));
            if let Some(r) = inst.results.first() {
                g.write(r, &rd);
            }
        }

        InstKind::Store { ty, v, p } => {
            let rv = g.read(v, "t1");
            let (rp, disp) = g.address(p, "t0");
            let width = access_width(g, *ty);
            g.line(format!("st.{width} {rv}, {disp}({rp})"));
        }

        // Address arithmetic is ordinary addition; there is no GEP to lower.
        InstKind::Offset { p, d } => {
            g.binary("add", ".trap", false, p, d, inst.results.first());
        }

        // Widening is a copy: a balanced value's high trits are already zero,
        // and there is no second extension to choose (AM §3.5).
        InstKind::Widen { a, .. } => {
            let ra = g.read(a, "t0");
            if let Some(r) = inst.results.first() {
                match g.regs.get(r).copied() {
                    Some(own) if own != ra => g.line(format!("add.wrap {own}, {ra}, zero")),
                    Some(_) => {}
                    None => g.write(r, &ra),
                }
            }
        }

        // Narrowing is `wrap`, the instruction the legalizer's mask becomes.
        InstKind::Trunc { a, to, .. } => {
            let ra = g.read(a, "t0");
            let n = to.width().unwrap_or(27);
            let rd = g.dest(inst.results.first(), "t2");
            g.line(format!("wrap    {rd}, {ra}, {n}"));
            if let Some(r) = inst.results.first() {
                g.write(r, &rd);
            }
        }

        InstKind::Call { callee, args, .. } => {
            if args.len() > 8 {
                g.errs
                    .push("more than eight arguments is not implemented".into());
                return;
            }
            // Arguments are read into `a0`…`a7` in order. Nothing allocated
            // is live here — the allocator gives a register only where no
            // call falls inside the live range — so writing them is safe.
            for (i, a) in args.iter().enumerate() {
                let reg = format!("a{i}");
                let from = g.read(a, &reg);
                if from != reg {
                    g.line(format!("add.wrap {reg}, {from}, zero"));
                }
            }
            match callee {
                Callee::Direct(name) => g.line(format!("call    f.{name}")),
                // An indirect call is `jalr` through the pointer, which is
                // the same linkage the direct form expands to.
                Callee::Indirect(p) => {
                    let rp = g.read(p, "t0");
                    g.line(format!("jalr    ra, 0({rp})"));
                }
            }
            if let Some(r) = inst.results.first() {
                match g.regs.get(r).copied() {
                    Some(own) if own != "a0" => g.line(format!("add.wrap {own}, a0, zero")),
                    Some(_) => {}
                    None => g.write(r, "a0"),
                }
            }
        }
    }
}

fn emit_term(g: &mut Gen, t: &Terminator, calls: bool) {
    match t {
        Terminator::Ret(v) => {
            if let Some(v) = v {
                let from = g.read(v, "a0");
                if from != "a0" {
                    g.line(format!("add.wrap a0, {from}, zero"));
                }
            }
            epilogue(g, calls);
        }

        Terminator::Br(target) => {
            move_args(g, target);
            // A jump to the block emitted next is a jump to the next
            // instruction. Binding the parameters still has to happen; the
            // transfer of control does not.
            if g.next_block.as_deref() != Some(target.label.as_str()) {
                let label = g.block_label(&target.label);
                g.line(format!("j       {label}"));
            }
        }

        // `br3` names its three targets itself wherever it can reach them.
        // An arm it cannot — a target with block arguments to bind, or one
        // out of the displacement's ±1093 words — goes through a stub holding
        // the edge's code and a jump, whose range is the whole address space.
        Terminator::Br3 { t, neg, zero, pos } => {
            let rt = g.read(t, "t0");
            let arms: Vec<(&Target, Option<String>)> = [neg, zero, pos]
                .into_iter()
                .map(|d| {
                    let stub = (!g.reaches(d)).then(|| g.fresh("b"));
                    (d, stub)
                })
                .collect();
            let named: Vec<String> = arms
                .iter()
                .map(|(d, stub)| match stub {
                    Some(s) => s.clone(),
                    None => g.block_label(&d.label),
                })
                .collect();
            g.line(format!(
                "br3     {rt}, {}, {}, {}",
                named[0], named[1], named[2]
            ));
            for (target, stub) in &arms {
                let Some(stub) = stub else { continue };
                g.label(stub);
                move_args(g, target);
                let label = g.block_label(&target.label);
                g.line(format!("j       {label}"));
            }
        }

        Terminator::Trap(code) => {
            g.line(format!("trap    {}", code.name()));
        }

        // Reaching `unreachable` is UB (TIR §4 item 1). A trap is the most useful
        // thing an implementation can do with it.
        Terminator::Unreachable => {
            g.line(format!("trap    {}", FaultCode::Trap.name()));
        }
    }
}

/// Bind a destination's block parameters, via the transfer area so that an
/// argument reading a slot another argument overwrites still sees the old
/// value.
fn move_args(g: &mut Gen, target: &Target) {
    if target.args.is_empty() {
        return;
    }
    let Some(dest) = g.func.block(&target.label) else {
        g.errs.push(format!("`^{}` is not a block", target.label));
        return;
    };
    let params: Vec<String> = dest.params.iter().map(|(n, _)| n.clone()).collect();
    if params.len() != target.args.len() {
        g.errs.push(format!(
            "`^{}` takes {} parameters, {} given",
            target.label,
            params.len(),
            target.args.len()
        ));
        return;
    }

    for (i, arg) in target.args.iter().enumerate() {
        let from = g.read(arg, "t0");
        let at = g.frame.transfer[i];
        g.line(format!("st.word {from}, {at}(sp)"));
    }
    for (i, p) in params.iter().enumerate() {
        let from = g.frame.transfer[i];
        g.line(format!("ld.word t0, {from}(sp)"));
        g.write(p, "t0");
    }
}

/// After legalizing for this target every arithmetic width is the word, and
/// `t1` survives only as a condition — which the machine reads by sign, so it
/// needs no conversion at all.
fn check_width(g: &mut Gen, ty: Type) {
    if let Type::Int(w) = ty
        && w != 27
        && w != 1
    {
        g.errs.push(format!(
            "t{w} arithmetic reached the backend; legalize for this target first"
        ));
    }
}

/// The access width of a load or store. Memory widths are not promoted by
/// legalization (`docs/spec-gaps.md` G6.3), so they arrive as written.
fn access_width(g: &mut Gen, ty: Type) -> &'static str {
    // An address is a word (TRISC-27 §2.1).
    if ty == Type::Ptr {
        return "word";
    }
    match ty.width() {
        Some(27) => "word",
        Some(w) if w <= 9 => "tryte",
        other => {
            g.errs.push(format!(
                "no machine access width for t{}",
                other.unwrap_or(0)
            ));
            "word"
        }
    }
}
