//! Code generation: legalized TIR to TRISC-27 assembly.
//!
//! The output is assembly text rather than an image, so the assembler owns
//! label resolution, instruction encoding and layout — one implementation of
//! each, in `tritium`, shared with the disassembler. It also means the
//! backend's output is readable, which matters a great deal while it is new.
//!
//! # The register allocator, and its absence
//!
//! Every SSA value gets a stack slot, and every instruction loads its
//! operands into scratch registers, computes, and stores the result back.
//! This is the simplest allocator that is correct, and the code it produces
//! is correspondingly slow — three memory accesses for an add. It is written
//! this way on purpose: an allocator is a large, subtle thing, and a backend
//! that is *obviously* right is the better first one to have. Values live in
//! `t0`–`t3`; nothing is kept in a register across an instruction boundary.
//!
//! # Why every branch is four instructions
//!
//! A `br3` displacement reaches ±1093 words (TRISC-27 §4.5), and a branch
//! that cannot reach is an assembly-time error rather than something the
//! assembler expands — expansion would make an instruction's size depend on
//! its operands. So each three-way branch is emitted as a `br3` into three
//! adjacent jumps, whose range is the whole address space. A peephole pass
//! should shorten the common case later.

use crate::tir::ir::*;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use trit_core::{FaultCode, Flavor};

/// Why a module could not be compiled.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct CodegenError {
    /// The function involved, if any.
    pub function: Option<String>,
    /// What could not be done.
    pub message: String,
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.function {
            Some(n) => write!(f, "@{n}: {}", self.message),
            None => write!(f, "{}", self.message),
        }
    }
}

impl std::error::Error for CodegenError {}

/// Trytes in a word.
const WORD: i128 = 3;

/// Round up to a whole number of words.
fn round_up(v: i128) -> i128 {
    (v + WORD - 1) / WORD * WORD
}

/// Compile a legalized module to TRISC-27 assembly.
///
/// `entry` names the function the generated start code calls; its result
/// becomes the machine's exit status.
pub fn compile(m: &Module, entry: &str) -> Result<String, Vec<CodegenError>> {
    let mut errs = Vec::new();
    let mut out = String::new();

    if m.function(entry).is_none() {
        errs.push(CodegenError {
            function: None,
            message: format!("`@{entry}` is not defined in this module"),
        });
    }

    // Only what the generated code actually uses: the device region is
    // unreachable from TIR (§5 has no integer-to-pointer cast), so the
    // character ports are the runtime's business, not this file's.
    let _ = writeln!(
        out,
        "; Generated by trustc from TIR. Target: TRISC-27.\n\
         \n\
         .equ MEM_SIZE, -6\n"
    );

    // Execution begins at address 0 (TRISC-27 §6.4), so the start code is
    // first: give the program a stack, call the entry function, and halt with
    // whatever it returned.
    let _ = writeln!(
        out,
        "_start:\n\
         \x20   ld.word sp, MEM_SIZE(zero)\n\
         \x20   call    f.{entry}\n\
         \x20   halt    a0\n"
    );

    for f in &m.funcs {
        match function(f) {
            Ok(text) => out.push_str(&text),
            Err(msgs) => errs.extend(msgs.into_iter().map(|message| CodegenError {
                function: Some(f.sig.name.clone()),
                message,
            })),
        }
    }

    for g in &m.globals {
        let _ = writeln!(out, "\n.align 3\ng.{}:", g.name);
        match &g.init {
            None => {
                let _ = writeln!(out, "    .zero {}", g.trytes);
            }
            Some(vals) => {
                // A relocation is emitted as a word holding the symbol's
                // address, which is where TIR §1.2's "the target decides the
                // number" is discharged.
                for item in vals {
                    match item {
                        InitItem::Tryte(v) => {
                            let _ = writeln!(out, "    .tryte {}", v.to_decimal());
                        }
                        InitItem::Addr(name) => {
                            let _ = writeln!(out, "    .word f.{name}");
                        }
                    }
                }
            }
        }
    }

    if errs.is_empty() { Ok(out) } else { Err(errs) }
}

/// Where a value lives: a displacement from `sp`.
struct Frame {
    /// Slot of each SSA value, in trytes from `sp`.
    slots: BTreeMap<String, i128>,
    /// Slots holding branch arguments in transit.
    transfer: Vec<i128>,
    /// Total frame size in trytes.
    size: i128,
}

/// Lay out the frame: one word per SSA value, plus `slot` storage, plus a
/// transfer area wide enough for the widest block parameter list.
///
/// The transfer area is what makes a jump with block arguments safe when an
/// argument reads a slot another argument is about to write — the loop back
/// edge that swaps two values is the case that matters. Arguments go to the
/// transfer slots first, and only then to the parameters.
fn layout(f: &Function) -> Frame {
    let mut slots = BTreeMap::new();
    let mut cursor = WORD; // word 0 holds the saved return address

    let mut give = |name: &str, cursor: &mut i128| {
        slots.entry(name.to_string()).or_insert_with(|| {
            let at = *cursor;
            *cursor += WORD;
            at
        });
    };

    for (n, _) in &f.sig.params {
        give(n, &mut cursor);
    }
    for b in &f.blocks {
        for (n, _) in &b.params {
            give(n, &mut cursor);
        }
        for i in &b.insts {
            for r in &i.results {
                give(r, &mut cursor);
            }
        }
    }

    // `slot` allocations are storage, not values: the value is the address.
    for b in &f.blocks {
        for i in &b.insts {
            if let InstKind::Slot { trytes } = &i.kind {
                let aligned = round_up(cursor);
                cursor = aligned + round_up(*trytes as i128);
                if let Some(name) = i.results.first() {
                    slots.insert(format!("\u{1}storage.{name}"), aligned);
                }
            }
        }
    }

    let widest = f.blocks.iter().map(|b| b.params.len()).max().unwrap_or(0);
    let transfer: Vec<i128> = (0..widest)
        .map(|_| {
            let at = cursor;
            cursor += WORD;
            at
        })
        .collect();

    Frame {
        slots,
        transfer,
        size: round_up(cursor),
    }
}

struct Gen<'a> {
    func: &'a Function,
    frame: Frame,
    out: String,
    errs: Vec<String>,
    counter: u32,
}

impl Gen<'_> {
    fn line(&mut self, text: impl AsRef<str>) {
        let _ = writeln!(self.out, "    {}", text.as_ref());
    }

    fn label(&mut self, text: impl AsRef<str>) {
        let _ = writeln!(self.out, "{}:", text.as_ref());
    }

    fn fresh(&mut self, what: &str) -> String {
        self.counter += 1;
        // The function's name is part of it: a local label is file-scoped,
        // and the counter restarts with every function.
        format!(".L{}.{what}{}", self.func.sig.name, self.counter)
    }

    fn slot(&mut self, name: &str) -> i128 {
        match self.frame.slots.get(name) {
            Some(s) => *s,
            None => {
                self.errs.push(format!("`%{name}` has no slot"));
                0
            }
        }
    }

    /// Load an operand into a register.
    fn read(&mut self, o: &Operand, reg: &str) {
        match o {
            Operand::Value(name) => {
                let at = self.slot(name);
                self.line(format!("ld.word {reg}, {at}(sp)"));
            }
            Operand::Const(_, v) => {
                self.line(format!("li      {reg}, {}", v.to_decimal()));
            }
            Operand::Global(g) => {
                self.line(format!("la      {reg}, g.{g}"));
            }
        }
    }

    /// Store a register into a value's slot.
    fn write(&mut self, name: &str, reg: &str) {
        let at = self.slot(name);
        self.line(format!("st.word {reg}, {at}(sp)"));
    }

    fn block_label(&self, block: &str) -> String {
        format!("f.{}.{}", self.func.sig.name, block)
    }
}

fn function(f: &Function) -> Result<String, Vec<String>> {
    let frame = layout(f);
    let calls = f.blocks.iter().any(|b| {
        b.insts
            .iter()
            .any(|i| matches!(i.kind, InstKind::Call { .. }))
    });

    let mut g = Gen {
        func: f,
        frame,
        out: String::new(),
        errs: Vec::new(),
        counter: 0,
    };

    let name = f.sig.name.clone();
    let _ = writeln!(g.out, "\n; {} — frame {} trytes", name, g.frame.size);
    // Instructions are word-aligned (TRISC-27 §3.1), and data of a length
    // that is not a multiple of three may precede this.
    let _ = writeln!(g.out, ".align 3");
    g.label(format!("f.{name}"));

    // Prologue. `sp` grows downward and stays word-aligned (§6.2).
    let size = g.frame.size;
    g.line(format!("addi.trap sp, sp, -{size}"));
    if calls {
        g.line("st.word ra, 0(sp)");
    }

    // Arguments arrive in a0…a7 and are spilled to their slots at once.
    for (i, (pname, _)) in f.sig.params.iter().enumerate() {
        if i >= 8 {
            g.errs
                .push("more than eight arguments is not implemented".into());
            break;
        }
        let at = g.slot(pname);
        g.line(format!("st.word a{i}, {at}(sp)"));
    }
    let entry = g.block_label(&f.blocks[0].label);
    g.line(format!("j       {entry}"));

    for b in &f.blocks {
        let label = g.block_label(&b.label);
        g.label(label);
        for inst in &b.insts {
            emit_inst(&mut g, inst, calls);
        }
        emit_term(&mut g, &b.term, calls);
    }

    if g.errs.is_empty() {
        Ok(g.out)
    } else {
        Err(g.errs)
    }
}

/// The epilogue, emitted at every `ret`.
fn epilogue(g: &mut Gen, calls: bool) {
    if calls {
        g.line("ld.word ra, 0(sp)");
    }
    let size = g.frame.size;
    g.line(format!("addi.trap sp, sp, {size}"));
    g.line("ret");
}

fn emit_inst(g: &mut Gen, inst: &Inst, _calls: bool) {
    match &inst.kind {
        InstKind::Flavored {
            op,
            flavor,
            a,
            b,
            ty,
        } => {
            check_width(g, *ty);
            g.read(a, "t0");
            g.read(b, "t1");
            let mnemonic = match op {
                FlavoredOp::Add => "add",
                FlavoredOp::Sub => "sub",
                FlavoredOp::Mul => "mul",
                FlavoredOp::Shl => "shl",
            };
            let suffix = flavor.suffix();
            if *flavor == Flavor::Flag {
                g.line(format!("{mnemonic}{suffix} t2, t0, t1, t3"));
                if let Some(r) = inst.results.first() {
                    g.write(r, "t2");
                }
                if let Some(r) = inst.results.get(1) {
                    g.write(r, "t3");
                }
            } else {
                g.line(format!("{mnemonic}{suffix} t2, t0, t1"));
                if let Some(r) = inst.results.first() {
                    g.write(r, "t2");
                }
            }
        }

        InstKind::Plain { op, a, b, ty } => {
            check_width(g, *ty);
            g.read(a, "t0");
            g.read(b, "t1");
            let mnemonic = match op {
                PlainOp::Div => "div",
                PlainOp::Rem => "rem",
                PlainOp::Shr => "shr",
                PlainOp::TMin => "tmin",
                PlainOp::TMax => "tmax",
                PlainOp::TMul => "tmul",
            };
            g.line(format!("{mnemonic}    t2, t0, t1"));
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        // Negation is `0 − x`; the machine needs no separate instruction
        // because `r0` is a register like any other (TRISC-27 §4.1).
        InstKind::Neg { a, ty } => {
            check_width(g, *ty);
            g.read(a, "t0");
            g.line("neg     t2, t0");
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        InstKind::Cmp { a, b, ty } => {
            check_width(g, *ty);
            g.read(a, "t0");
            g.read(b, "t1");
            g.line("cmp     t2, t0, t1");
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        // One instruction, three arms, no branch.
        InstKind::Select3 {
            t,
            neg,
            zero,
            pos,
            ty,
        } => {
            check_width(g, *ty);
            g.read(t, "t0");
            g.read(neg, "t1");
            g.read(zero, "t2");
            g.read(pos, "t3");
            g.line("sel3    t2, t0, t1, t2, t3");
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        // The value of a `slot` is the address of its storage in the frame.
        InstKind::Slot { .. } => {
            if let Some(r) = inst.results.first() {
                let at = g.slot(&format!("\u{1}storage.{r}"));
                g.line(format!("addi.trap t0, sp, {at}"));
                g.write(r, "t0");
            }
        }

        InstKind::Load { ty, p } => {
            g.read(p, "t0");
            let width = access_width(g, *ty);
            g.line(format!("ld.{width} t2, 0(t0)"));
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        InstKind::Store { ty, v, p } => {
            g.read(v, "t1");
            g.read(p, "t0");
            let width = access_width(g, *ty);
            g.line(format!("st.{width} t1, 0(t0)"));
        }

        // Address arithmetic is ordinary addition; there is no GEP to lower.
        InstKind::Offset { p, d } => {
            g.read(p, "t0");
            g.read(d, "t1");
            g.line("add.trap t2, t0, t1");
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        // Widening is a copy: a balanced value's high trits are already zero,
        // and there is no second extension to choose (AM §3.5).
        InstKind::Widen { a, .. } => {
            g.read(a, "t0");
            if let Some(r) = inst.results.first() {
                g.write(r, "t0");
            }
        }

        // Narrowing is `wrap`, the instruction the legalizer's mask becomes.
        InstKind::Trunc { a, to, .. } => {
            g.read(a, "t0");
            let n = to.width().unwrap_or(27);
            g.line(format!("wrap    t2, t0, {n}"));
            if let Some(r) = inst.results.first() {
                g.write(r, "t2");
            }
        }

        InstKind::Call { callee, args, .. } => {
            if args.len() > 8 {
                g.errs
                    .push("more than eight arguments is not implemented".into());
                return;
            }
            for (i, a) in args.iter().enumerate() {
                let reg = format!("a{i}");
                g.read(a, &reg);
            }
            match callee {
                Callee::Direct(name) => g.line(format!("call    f.{name}")),
                // An indirect call is `jalr` through the pointer, which is
                // the same linkage the direct form expands to.
                Callee::Indirect(p) => {
                    g.read(p, "t0");
                    g.line("jalr    ra, 0(t0)");
                }
            }
            if let Some(r) = inst.results.first() {
                g.write(r, "a0");
            }
        }
    }
}

fn emit_term(g: &mut Gen, t: &Terminator, calls: bool) {
    match t {
        Terminator::Ret(v) => {
            if let Some(v) = v {
                g.read(v, "a0");
            }
            epilogue(g, calls);
        }

        Terminator::Br(target) => {
            move_args(g, target);
            let label = g.block_label(&target.label);
            g.line(format!("j       {label}"));
        }

        // A `br3` into three adjacent jumps: the branch displacements are
        // always 1, 2 and 3 words, so they always reach, and the jumps reach
        // the whole address space.
        Terminator::Br3 { t, neg, zero, pos } => {
            g.read(t, "t0");
            let names = [g.fresh("bn"), g.fresh("bz"), g.fresh("bp")];
            g.line(format!(
                "br3     t0, {}, {}, {}",
                names[0], names[1], names[2]
            ));
            for (name, target) in names.iter().zip([neg, zero, pos]) {
                g.label(name);
                move_args(g, target);
                let label = g.block_label(&target.label);
                g.line(format!("j       {label}"));
            }
        }

        Terminator::Trap(code) => {
            g.line(format!("trap    {}", code.name()));
        }

        // Reaching `unreachable` is UB (TIR §4 item 1). A trap is the most useful
        // thing an implementation can do with it.
        Terminator::Unreachable => {
            g.line(format!("trap    {}", FaultCode::Trap.name()));
        }
    }
}

/// Bind a destination's block parameters, via the transfer area so that an
/// argument reading a slot another argument overwrites still sees the old
/// value.
fn move_args(g: &mut Gen, target: &Target) {
    if target.args.is_empty() {
        return;
    }
    let Some(dest) = g.func.block(&target.label) else {
        g.errs.push(format!("`^{}` is not a block", target.label));
        return;
    };
    let params: Vec<String> = dest.params.iter().map(|(n, _)| n.clone()).collect();
    if params.len() != target.args.len() {
        g.errs.push(format!(
            "`^{}` takes {} parameters, {} given",
            target.label,
            params.len(),
            target.args.len()
        ));
        return;
    }

    for (i, arg) in target.args.iter().enumerate() {
        g.read(arg, "t0");
        let at = g.frame.transfer[i];
        g.line(format!("st.word t0, {at}(sp)"));
    }
    for (i, p) in params.iter().enumerate() {
        let from = g.frame.transfer[i];
        g.line(format!("ld.word t0, {from}(sp)"));
        g.write(p, "t0");
    }
}

/// After legalizing for this target every arithmetic width is the word, and
/// `t1` survives only as a condition — which the machine reads by sign, so it
/// needs no conversion at all.
fn check_width(g: &mut Gen, ty: Type) {
    if let Type::Int(w) = ty
        && w != 27
        && w != 1
    {
        g.errs.push(format!(
            "t{w} arithmetic reached the backend; legalize for this target first"
        ));
    }
}

/// The access width of a load or store. Memory widths are not promoted by
/// legalization (`docs/spec-gaps.md` G6.3), so they arrive as written.
fn access_width(g: &mut Gen, ty: Type) -> &'static str {
    // An address is a word (TRISC-27 §2.1).
    if ty == Type::Ptr {
        return "word";
    }
    match ty.width() {
        Some(27) => "word",
        Some(w) if w <= 9 => "tryte",
        other => {
            g.errs.push(format!(
                "no machine access width for t{}",
                other.unwrap_or(0)
            ));
            "word"
        }
    }
}
