//! Emit the echo program of TRISC-27's Appendix A as a textual image.
//!
//! This exists because the assembler does not: until `.t27` source can be
//! assembled, the encoder in `tritium::inst` is the only way to produce an
//! image, and a checked-in example is worth more than a description of one.
//!
//! ```text
//! cargo run -p tritium --example emit_echo > examples/trisc/echo.timg
//! ```

use trit_core::Flavor;
use tritium::vm::device;
use tritium::{AluOp, Inst, Reg, Width, image};

fn r(name: &str) -> Reg {
    Reg::from_name(name).expect("a register")
}

fn main() {
    let zero = Reg::ZERO;
    let program = [
        // start: sp ← A, so the program works on any address-space size.
        Inst::Load {
            width: Width::Word,
            rd: r("sp"),
            rs1: zero,
            imm: device::MEM_SIZE,
        },
        // loop: a0 ← IO_IN
        Inst::Load {
            width: Width::Tryte,
            rd: r("a0"),
            rs1: zero,
            imm: device::IO_IN,
        },
        Inst::Alu {
            op: AluOp::Cmp,
            flavor: Flavor::Wrap,
            rd: r("t0"),
            rs1: r("a0"),
            rs2: zero,
            rc: zero,
        },
        // negative → check_eof; zero or positive → echo
        Inst::Br3 {
            rs1: r("t0"),
            neg: 1,
            zero: 3,
            pos: 3,
        },
        // check_eof: −1 (waiting) → 0, −2 (closed) → −1
        Inst::AluI {
            op: AluOp::Add,
            flavor: Flavor::Wrap,
            rd: r("t1"),
            rs1: r("a0"),
            imm: 1,
        },
        Inst::Br3 {
            rs1: r("t1"),
            neg: 3,
            zero: -4,
            pos: 2,
        },
        // echo: IO_OUT ← a0
        Inst::Store {
            width: Width::Tryte,
            rs2: r("a0"),
            rs1: zero,
            imm: device::IO_OUT,
        },
        Inst::Jal { rd: zero, off: -6 },
        // done:
        Inst::Halt { rs1: zero },
    ];

    let trytes: Vec<i16> = program
        .iter()
        .flat_map(|inst| tritium::word::word_trytes(inst.encode()))
        .collect();

    print!("{}", ECHO_HEADER);
    print!("{}", image::render(&trytes));
}

const ECHO_HEADER: &str = "\
; echo — the worked program of TRISC-27 Appendix A.
;
; Reads the input port until it closes, writing every code unit back out.
; Both of its branches are three-way: \"code unit / waiting / closed\", then
; \"still waiting / closed\".
;
; Generated by `cargo run -p tritium --example emit_echo`; regenerate it from
; assembly source once an assembler exists.
;
";
